// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzEF71Kky1J96B_jloeaJFSO28Ac8EGPM',
    appId: '1:920805870636:web:65a8a4518a71263d2cd589',
    messagingSenderId: '920805870636',
    projectId: 'kaaspunten',
    authDomain: 'kaaspunten.firebaseapp.com',
    storageBucket: 'kaaspunten.appspot.com',
    measurementId: 'G-1W4Y889NVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeJxVV2zLhRBnznlzGKN_-52mVTAXkNw',
    appId: '1:920805870636:android:849f6e3d58cd0c0f2cd589',
    messagingSenderId: '920805870636',
    projectId: 'kaaspunten',
    storageBucket: 'kaaspunten.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3FKT7H_Xu__2B1AJ4yjhWBHqLDBb7GA',
    appId: '1:920805870636:ios:b1832c507f5afaf12cd589',
    messagingSenderId: '920805870636',
    projectId: 'kaaspunten',
    storageBucket: 'kaaspunten.appspot.com',
    iosBundleId: 'com.example.kaasPunten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3FKT7H_Xu__2B1AJ4yjhWBHqLDBb7GA',
    appId: '1:920805870636:ios:b1832c507f5afaf12cd589',
    messagingSenderId: '920805870636',
    projectId: 'kaaspunten',
    storageBucket: 'kaaspunten.appspot.com',
    iosBundleId: 'com.example.kaasPunten',
  );
}
